name: CI
on:
  push:
    branches:
      - release/v*
      - main
      - alpha

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: ./.github/composite-workflows/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: ./.github/composite-workflows/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm test
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: ./.github/composite-workflows/setup-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm run compile
